Initial version
reshufflehq/reshuffle-airtable-connector pull request #1
Opened 2021-01-27 20:34 UTC by zacmos

2021-01-28 00:39 UTC, duckranger requested changes

2021-01-28 21:24 UTC, zacmos commented on README.md
> +[SDK](#sdk) - Retrieve a full Airtable sdk object
Changed the base description

2021-01-28 21:32 UTC, zacmos commented on src/index.ts
> +// In order to get the tables names, need to access the metadata APIs - request for each connector
These were my comments for issues with the connector, I removed them.

2021-01-28 22:18 UTC, zacmos commented on src/index.ts
> +      options.type !== 'RecordDeleted'
`if (!Object.values(AirtableEventType).includes(options.type)) ` ends up with 
`error TS2693: 'AirtableEventType' only refers to a type, but is being used as a value here.`

2021-01-31 20:41 UTC, duckranger approved these changes

2021-02-01 22:20 UTC, merged